### ISSUE TITLE
The balance displayed in the "popup to skake" is not up to date

### ISSUE THREAD

**Issue by GuiGou12358** [PlasmNetwork/astar-apps#140]
After the user stakes or unstakes on dApps, the balance displayed when staking on a new dApps is not up to date. 
It means the checks done in the UI side to not stake more than your balance is not efficient anymore.

**Comment by impelcrypto** [comment]
Hi @GuiGou12358 
Could you try it again as the issue has been fixed on my end. Thank you.

**Comment by GuiGou12358** [comment]
The issue is fixed. Thanks!
