### ISSUE TITLE
[Feature suggestion] Change theme/logo when Shiden network is chosen in the dApps Store 

### ISSUE THREAD

**Issue by RoyalCT** [PlasmNetwork/astar-apps#147]
**Motivation**
Shiden needs its own identity, it’s own feel and vibe. It’s better for making it easier for User interaction with the store as it makes it less confusing when switching to Shiden network changes the actual style of the visuals. The community agrees with this, and this has been posted as a proposal on the forum. Our project leader Sota seems to approve and support this approach. 

Here is the link for the proposal:

https://forum.astar.network/t/website-improvements-to-help-growth-of-shiden/1965

**Suggested Solution**

- change pallet colors/theme when choosing Shiden network on the dApp Store. 
- change the logo to Shiden when detecting change in network to Shiden Network. 

**Alternatives**
- no need to make a new theme, you can instead use the current dark theme already implemented, and change just the logo. So changing the network to Shiden will make it change to current DarkTheme we have and the only thing needed then is changing the logo. 

**Additional information**
Good luck, and for the developers I trust you will achieve far more than what you think you can. You are building the future. 🤞

**Comment by impelcrypto** [comment]
Fixed this in https://github.com/PlasmNetwork/astar-apps/pull/175
