### ISSUE TITLE
Dark/Light Mode

### ISSUE THREAD

**Issue by SotaWatanabe** [PlasmNetwork/astar-apps#23]
<img width="274" alt="Screenshot 2021-10-06 at 3 24 20 PM" src="https://user-images.githubusercontent.com/29359048/136151236-d954e30e-bb29-487d-b1bb-ef7973fab0e3.png">

The dark mode is not enabled but during my night it automatically becomes the dark mode

**Comment by togamamora** [comment]
I am on Math Wallet for android, dark mode doesn't seem to work.

![Screenshot_20211006_211647_com medishares android](https://user-images.githubusercontent.com/37278708/136209961-3d5397fa-ad14-4021-bdf9-6bbc14af8beb.jpg)

**Comment by hoonsubin** [comment]
fixed with https://github.com/PlasmNetwork/astar-apps/pull/72
