### ISSUE TITLE
UI workflow issues with staking account selection

### ISSUE THREAD

**Issue by anaelleltd** [PlasmNetwork/astar-apps#43]
If I try to select an account that is already selected, the UI becomes un-responsive and I'm stuck. I have to close the modal/reload the whole page to overcome this issue. 

If I click "stake" from this view, the Polkadot-JS modal pops up, even though I haven't even set a value for the SBY to be staked!

![Bug_stuck](https://user-images.githubusercontent.com/44770354/136335098-0a803148-cf7a-4325-9c38-298880ae29a3.JPG)

I think a better UX would be to close the modal automatically upon selecting a wallet, including clicking on a wallet that is already selected. 👀

**Comment by impelcrypto** [comment]
Fixed in https://github.com/PlasmNetwork/astar-apps/pull/155
