### ISSUE TITLE
[Bug report] Vue.js devtools can't detect the app

### ISSUE THREAD

**Issue by impelcrypto** [PlasmNetwork/astar-apps#55]
**Describe the bug**

Can't use [Vue.js devtools](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd) in localhost. 
<img width="926" alt="image" src="https://user-images.githubusercontent.com/92044428/136651948-439571b2-7378-4504-8cd3-ebd0fec28ff5.png">

**To Reproduce**
1. Install extension on Chrome
2. Run the app via `yarn dev`

**Expected behavior**
> A clear and concise description of what you expected to happen.

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information)**
 
Extension version: 5.3.4
Chrome version:  94.0.4606.71 (Official Build) (x86_64)

<img width="523" alt="image" src="https://user-images.githubusercontent.com/92044428/136651987-e9ddf5db-8806-4806-9dae-1d8a3df645ca.png">

**Smartphone (please complete the following information)**

**Additional information**
> Add any other information about the problem here.

**Comment by sirius651** [comment]
For vue3, it seems old devtools is not work. instead, try this https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd
