### ISSUE TITLE
[Bug report] Metamask send all funds bug

### ISSUE THREAD

**Issue by Dawido0** [PlasmNetwork/astar-apps#71]
Metamask ... it is impossible to send all funds from the metamask account ... transaction cost is 0.1 SBN fee - so when sending all funds - the transaction will be successful - but will only charge 0.1 SBN fee.

![dzvdzv](https://user-images.githubusercontent.com/92333188/136843376-2b725ab3-5c7d-4bd4-9996-e5930e55f7fa.png)

**Comment by impelcrypto** [comment]
Fixed this in https://github.com/PlasmNetwork/astar-apps/pull/84
